In [1]:
import pandas as pd

In [2]:
all_cases = pd.read_csv('./raw data/cv88on.txt',
                        delimiter = "\t",
                        encoding="latin1",
                        low_memory=False)

In [3]:
all_cases

,CIRCUIT,DISTRICT,OFFICE,DOCKET,ORIGIN,FILEDATE,FDATEUSE,JURIS,NOS,TITL,...,JUDGMENT,DJOINED,PRETRIAL,TRIBEGAN,TRIALEND,TRMARB,PROSE,IFP,STATUSCD,TAPEYEAR
0,0,90,1,7101462,4,07/21/1971,07/01/1971,3,440,NaN,...,1,NaN,NaN,NaN,NaN,-8,-8,NaN,NaN,1988
1,0,90,1,7300974,4,05/17/1973,02/01/1983,2,890,NaN,...,1,01/20/1988,NaN,NaN,NaN,-8,-8,NaN,NaN,1988
2,0,90,1,7601326,4,01/31/1985,06/01/1985,2,440,NaN,...,-8,NaN,NaN,NaN,NaN,-8,-8,NaN,NaN,1988
3,0,90,1,7700081,3,09/19/1984,05/01/1986,2,442,NaN,...,-8,NaN,NaN,NaN,NaN,-8,-8,NaN,NaN,1988
4,0,90,1,7901559,2,06/15/1979,06/01/1979,2,550,NaN,...,2,NaN,NaN,NaN,NaN,-8,-8,NaN,NaN,1988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9676637,11,3J,6,2200045,1,06/14/2022,06/01/2022,3,555,42,...,-8,NaN,NaN,NaN,NaN,-8,1,FP,S,2099
9676638,11,3J,6,2200046,1,06/16/2022,06/01/2022,3,530,28,...,-8,NaN,NaN,NaN,NaN,-8,1,FP,S,2099
9676639,11,3J,6,2200047,1,06/21/2022,06/01/2022,3,440,42,...,-8,NaN,NaN,NaN,NaN,-8,1,-8,S,2099
9676640,11,3J,6,2200048,1,06/21/2022,06/01/2022,3,440,42,...,-8,NaN,NaN,NaN,NaN,-8,1,-8,S,2099
9676641,11,3J,6,2200049,1,06/21/2022,06/01/2022,3,440,42,...,-8,NaN,NaN,NaN,NaN,-8,1,-8,S,2099